name: gcp-deployer

on:
  push:
    branches: [deploy-prod]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Deploy and restart web server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
        run: |
          cd server
          npm install
          PORT=80 ENV=production npm run start:prod
